---
extends: airbnb-base
env:
  node: true
  es6: true
rules:
  no-unused-vars:
    - error
    -
      argsIgnorePattern: "_.*"
      varsIgnorePattern: "_.*"
  import/extensions:
    # browsers don't grok short-hands for './x.js'
    - off
  spaced-comment:
    # conflicts with flow type annotation comments
    - off
  no-console:
    - off
  no-use-before-define:
    - error
    - nofunc
  prefer-destructuring:
    - error
    # { x } = y doesn't parse
    - AssignmentExpression:
        array: false
        object: false
  indent:
    - error
    - 2
    # emacs compat
    -
      CallExpression:
        arguments: first
      MemberExpression: off
  object-curly-newline:
    - error
    -
      ObjectExpression:
        multiline: true
      ObjectPattern:
        # Don't discourage long-ish lists of named powerful objects.
        multiline: true
        minProperties: 7
